[package]
name = "libopal"
version = "0.1.0"
edition = "2024"

[dependencies]
safa-api = { version = "0.4.3", git = "https://github.com/SafaOS/safa-api", features = ["std"] }
opal-abi = { path = "../opal-abi" }
